export const data = {
  bio: {
    name: "Ahmed Benyoucef",
    tagline: "Développeur Full-Stack",
    email: "abenyoucef673@email.com",
    github: "https://github.com/abhamoud",
    website: "https://www.ahbenyoucef.com",
    linkedin: "https://www.linkedin.com/in/benyoucef-ahmed-8b6859200/",
    objective: "Pour créer les meilleures applications mobiles.",
  },
  skills: ["Parler Anglais", "Développeur Web certifié", "Visual Basic 6"],
  positions: [
    {
      id: "1",
      title: "Directeur de l'ingénierie",
      company: "AugustinIOS",
      startDate: "2019-11-01",
      endDate: null,
      employmentType: "À PLEIN TEMPS",
      location: "Birkhadem, Alger",
      achievements: [
        "Mentorat des développeurs, exécution 1 contre 1, recherche d'opportunités de formation, direction d'un groupe de pairs de développeurs au sein de AugustinIOS, organisation de déjeuners d'équipe et d'apprentissages",
        "Embaucher, aligner les ressources d'ingénierie avec les plans d'affaires, développer les cheminements de carrière et les aligner sur la rémunération",
        "Développement d'applications PHP et jANGO, fonctionnant avec Android Studio, Sql BDD, HTML",
      ],
    },
    {
      id: "2",
      title: "Développeur Principal",
      company: "Milistone",
      startDate: "2019-05-01",
      endDate: "2019-11-01",
      employmentType: "À PLEIN TEMPS",
      location: "Bab Ezouar, Alger",
      achievements: [
        "Construire une grande application PHP alimentant www.Milistone.com",
        "Travailler avec HTML, Wordpress, CSS et .NET pour créer des sites Web interactifs.",
        "Création et déploiement de fonctions serveur.",
      ],
    },
    {
      id: "3",
      title: "Consultant logiciel senior",
      company: "KeanMGM",
      startDate: "2017-03-01",
      endDate: "2019-05-01",
      employmentType: "À PLEIN TEMPS",
      location: "El Biar, Alger",
      achievements: [
        "Construire une grande application Mobile alimentant + IOS",
        "Travailler avec HTML, Wordpress, CSS et .NET pour créer des sites Web interactifs.",
        "Création et déploiement de fonctions serveur.",
      ],
    },
    {
      id: "4",
      title: "Devellopeur de logiciel confirmé",
      company: "ITcadre",
      startDate: "2016-02-01",
      endDate: "2017-03-01",
      employmentType: "À PLEIN TEMPS",
      location: "Sahouala, Alger",
      achievements: [
        "Développer des Application Mobile et des intégrations à l'aide de Ruby on Rails pour aider les consommateurs à gérer les factures de leur famille partout dans le monde.",
      ],
    },
    {
      id: "5",
      title: "Devellopeur",
      company: "LeadTech",
      startDate: "2015-08-01",
      endDate: "2016-02-01",
      employmentType: "À PLEIN TEMPS",
      location: "BirMoradRais, Alger",
      achievements: [
        "Je travaille avec des données sportives. Traitement des flux de données entrants, création de systèmes de gestion d'administration et BDD utilisés par les clients iOS, Android et Web. Les technologies impliquées sont Ruby on Rails, Python et MySQL.",
      ],
    },
  ],
};